### ISSUE TITLE
Problem with V-REP two-link arm example

### ISSUE THREAD

**Issue by neildhir** [studywolf/blog#5]
I am so sorry for opening yet another of these. This really must be the issue at my end, but just in case it is not; the two-link arm example is not running out of the box either:

![image](https://cloud.githubusercontent.com/assets/5817673/23175384/22b80a56-f857-11e6-8d2e-b6abbe443b6d.png)

The second link, top, is continuously reflecting about the top joint, suggesting there is a sign that's gone wrong somewhere.

**Comment by studywolf** [comment]
Looks like it was a time step issue, dropped it from .01s to .001s and that took care of it!
